
server:
  port: 8762

spring:
  application:
    name: Config-Server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yogesh-Kushwah/Flight-Booking-ConfigServer
          clone-on-start: true
